name: Alykhan Kanji
exclude: [README.md, LICENSE.md, CNAME, Gemfile, Gemfile.lock, vendor]
permalink: blog/:categories/:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "post"
    values:
      layout: "post"
