name: Alykhan Kanji
description: The website of Alykhan Kanji. See Alykhan's social media profiles and professional portfolio.
url: http://alykhan.com
exclude: [README.md, LICENSE.md, CNAME, Gemfile, Gemfile.lock, vendor]
permalink: blog/:categories/:year/:month/:day/:title/
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
